[project]
name = "dev-dependencies"
version = "0.1.0"
description = "Shared dev tooling (ruff, ty) for CDM projects"
readme = "README.md"
authors = [
    { name = "Aron Radics", email = "ajradics@yext.com" }
]
requires-python = ">=3.9"
dependencies = [
    "ruff>=0.14.1",
    "ty>=0.0.18",
    "pytest>=8.4.2",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
