"""add token to device

Revision ID: 08823b2939f3
Revises: 5863a99ceb6e
Create Date: 2024-12-21 21:26:16.008245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08823b2939f3'
down_revision: Union[str, None] = '5863a99ceb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'token')
    # ### end Alembic commands ###
