"""add settings field to devices table

Revision ID: 12725d34ffd6
Revises: 1f8667162460
Create Date: 2024-12-31 11:08:11.704965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12725d34ffd6'
down_revision: Union[str, None] = '1f8667162460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'settings')
    # ### end Alembic commands ###
