"""changed to added_date

Revision ID: 1f8667162460
Revises: 4625ca5cee01
Create Date: 2024-12-31 00:33:18.737310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f8667162460'
down_revision: Union[str, None] = '4625ca5cee01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('added_date', sa.DateTime(), nullable=True))
    op.drop_column('torrents', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    op.drop_column('torrents', 'added_date')
    # ### end Alembic commands ###
