"""added start date

Revision ID: 4625ca5cee01
Revises: 11eab43c042f
Create Date: 2024-12-31 00:14:45.971968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4625ca5cee01'
down_revision: Union[str, None] = '11eab43c042f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torrents', 'start_date')
    # ### end Alembic commands ###
