"""set bigint for total size

Revision ID: 4ab96c5b70ed
Revises: 73ee9852f6b5
Create Date: 2024-12-30 21:57:41.392929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ab96c5b70ed'
down_revision: Union[str, None] = '73ee9852f6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('torrents', 'total_size',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('torrents', 'total_size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
