"""add devices table

Revision ID: 5863a99ceb6e
Revises: 604fd767e6c8
Create Date: 2024-12-21 19:20:56.124006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5863a99ceb6e'
down_revision: Union[str, None] = '604fd767e6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'updated')
    # ### end Alembic commands ###
