"""add devices table

Revision ID: 604fd767e6c8
Revises: c17390c8ccb2
Create Date: 2024-12-21 19:13:18.609742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '604fd767e6c8'
down_revision: Union[str, None] = 'c17390c8ccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('devices')
    # ### end Alembic commands ###
