"""add torrents table

Revision ID: 73ee9852f6b5
Revises: cd1a6612aff5
Create Date: 2024-12-30 21:50:36.884629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ee9852f6b5'
down_revision: Union[str, None] = 'cd1a6612aff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('download_dir', sa.String(length=255), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('eta', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torrents')
    # ### end Alembic commands ###
