"""rename available to progress

Revision ID: a10117205c0b
Revises: 4ab96c5b70ed
Create Date: 2024-12-30 22:48:41.961088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a10117205c0b'
down_revision: Union[str, None] = '4ab96c5b70ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('progress', sa.Float(), nullable=True))
    op.drop_column('torrents', 'available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('available', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('torrents', 'progress')
    # ### end Alembic commands ###
