"""is_admin is bool

Revision ID: c17390c8ccb2
Revises: 9e4eaa6173b4
Create Date: 2024-12-20 01:13:55.251338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17390c8ccb2'
down_revision: Union[str, None] = '9e4eaa6173b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
