"""add file path to devices

Revision ID: cd1a6612aff5
Revises: e9dc4d610e97
Create Date: 2024-12-21 23:53:08.002247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd1a6612aff5'
down_revision: Union[str, None] = 'e9dc4d610e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('file_list', sa.JSON(), nullable=True))
    op.drop_column('devices', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('devices', 'file_list')
    # ### end Alembic commands ###
