"""add file path to devices

Revision ID: e9dc4d610e97
Revises: 08823b2939f3
Create Date: 2024-12-21 23:11:18.549331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9dc4d610e97'
down_revision: Union[str, None] = '08823b2939f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'file_path')
    # ### end Alembic commands ###
