version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: dev_container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ..:/app

volumes:
  mysql_data:
